Homework2
================
Yahan Xue
2026-10-04

# Problem 1

``` r
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = entry == "YES"
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
subway_df |>
  distinct(station_name, line) |>
  nrow()
```

    ## [1] 465

``` r
subway_df |>
  filter(ada == TRUE) |>
  distinct(station_name, line) |>
  nrow()
```

    ## [1] 84

# Problem 2

``` r
library(readxl)

mr_trash = 
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.numeric(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

professor_trash = 
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M134"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.numeric(year),
    trash_wheel = "Professor Trash Wheel"
  )

gwynnda_trash = 
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L351"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.numeric(year),
    trash_wheel = "Gwynnda"
  )

trash_wheel_df = 
  bind_rows(
    mr_trash,
    professor_trash,
    gwynnda_trash
  )

nrow(trash_wheel_df)
```

    ## [1] 1188

``` r
trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         282.

``` r
trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

The combined Trash Wheel dataset consists of 1188 observations. Its key
variables are dumpster number, month, year, weight of trash collected in
tons, volume, homes powered, cigarette butts, and the Trash Wheel
identifier. Data were imported from the three corresponding Excel
worksheets; non‑data rows were removed during data cleaning, and all
records were merged to form a single tidy dataset. Professor Trash Wheel
collected a total of 282.26 tons of trash across the dataset. For June
2022, Gwynnda recorded a total collection of 18,120 cigarette butts.

# Problem 3

``` r
mci_baseline = 
  read_csv(
    "data/MCI_baseline.csv",
    skip = 1,
    na = "."
  ) |>
  janitor::clean_names() |>
  mutate(
    sex = if_else(sex == 1, "Male", "Female"),
    apoe4 = if_else(apoe4 == 1, "Carrier", "Non-carrier")
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ##  1     1        63.1 Female        16 Carrier             NA  
    ##  2     2        65.6 Female        20 Carrier             NA  
    ##  3     3        62.5 Male          16 Carrier             66.8
    ##  4     4        69.8 Female        16 Non-carrier         NA  
    ##  5     5        66   Male          16 Non-carrier         68.7
    ##  6     6        62.5 Male          16 Non-carrier         NA  
    ##  7     7        66.5 Male          18 Non-carrier         74  
    ##  8     8        67.2 Female        18 Non-carrier         NA  
    ##  9     9        66.7 Female        16 Non-carrier         NA  
    ## 10    10        64.1 Female        18 Non-carrier         NA  
    ## # ℹ 469 more rows

``` r
nrow(mci_baseline)
```

    ## [1] 479

``` r
mci_baseline |>
  filter(!is.na(age_at_onset)) |>
  nrow()
```

    ## [1] 93

``` r
mean(mci_baseline$current_age)
```

    ## [1] 65.0286

``` r
mci_baseline |>
  filter(sex == "Female") |>
  summarize(
    proportion_apoe4 = mean(apoe4 == "Carrier")
  )
```

    ## # A tibble: 1 × 1
    ##   proportion_apoe4
    ##              <dbl>
    ## 1              0.3

``` r
mci_amyloid = 
  read_csv(
    "data/mci_amyloid.csv",
    skip = 1,
    na = c("NA", "Na")
  ) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    cols = baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_ratio"
  ) |>
  mutate(
    time = case_when(
      visit == "baseline" ~ 0,
      visit == "time_2" ~ 2,
      visit == "time_4" ~ 4,
      visit == "time_6" ~ 6,
      visit == "time_8" ~ 8
    )
  ) |>
  select(id, time, amyloid_ratio)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_amyloid
```

    ## # A tibble: 2,435 × 3
    ##       id  time amyloid_ratio
    ##    <dbl> <dbl>         <dbl>
    ##  1     1     0         0.111
    ##  2     1     2        NA    
    ##  3     1     4         0.109
    ##  4     1     6         0.105
    ##  5     1     8         0.107
    ##  6     2     0         0.107
    ##  7     2     2         0.109
    ##  8     2     4         0.109
    ##  9     2     6         0.106
    ## 10     2     8         0.107
    ## # ℹ 2,425 more rows

``` r
baseline_only = 
  mci_baseline |>
  anti_join(
    mci_amyloid |> distinct(id),
    by = "id"
  )

amyloid_only = 
  mci_amyloid |>
  distinct(id) |>
  anti_join(
    mci_baseline,
    by = "id"
  )

baseline_only$id
```

    ## [1]  14  49  92 179 268 304 389 412

``` r
amyloid_only$id
```

    ##  [1]  72 234 283 380 484 485 486 487 488 489 490 491 492 493 494 495

``` r
mci_combined = 
  inner_join(
    mci_baseline,
    mci_amyloid,
    by = "id"
  )

mci_combined
```

    ## # A tibble: 2,355 × 8
    ##       id current_age sex    education apoe4   age_at_onset  time amyloid_ratio
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>          <dbl> <dbl>         <dbl>
    ##  1     1        63.1 Female        16 Carrier           NA     0         0.111
    ##  2     1        63.1 Female        16 Carrier           NA     2        NA    
    ##  3     1        63.1 Female        16 Carrier           NA     4         0.109
    ##  4     1        63.1 Female        16 Carrier           NA     6         0.105
    ##  5     1        63.1 Female        16 Carrier           NA     8         0.107
    ##  6     2        65.6 Female        20 Carrier           NA     0         0.107
    ##  7     2        65.6 Female        20 Carrier           NA     2         0.109
    ##  8     2        65.6 Female        20 Carrier           NA     4         0.109
    ##  9     2        65.6 Female        20 Carrier           NA     6         0.106
    ## 10     2        65.6 Female        20 Carrier           NA     8         0.107
    ## # ℹ 2,345 more rows

``` r
n_distinct(mci_combined$id)
```

    ## [1] 471

``` r
dim(mci_combined)
```

    ## [1] 2355    8

``` r
write_csv(
  mci_combined,
  "data/mci_combined.csv"
)
```

Following cleaning of the baseline demographic dataset, 479 participants
satisfied the study’s inclusion criteria. Of these individuals, 93
progressed to MCI over the follow‑up period. The mean baseline age was
roughly 65.03 years, and 30% of female participants were APOE4 carriers.

The amyloid biomarker dataset was imported and converted from wide
format to long format, such that each row corresponds to one participant
for a single study visit. Cross‑comparison of participant IDs between
the two datasets revealed 8 participants present exclusively in the
baseline dataset and 16 participants found only within the amyloid
biomarker dataset. An inner join was subsequently performed, yielding a
final sample of 471 participants common to both datasets. This merged
dataset integrates baseline demographic data with longitudinal amyloid
measurements and was saved and exported in CSV file format.
